### ISSUE TITLE
Falta alimentação direta do quadro

### ISSUE THREAD

**Issue by josemotta** [recreiocanoas/radar#1]
**Local:** Sede
**Etapas:**
- [x] Identificar as três fases no quadro de alimentação da sede (R, S, T)
- [x] Obter planta da sede
- [ ] Identificar na planta tomadas da sede
- [ ] Providenciar troca disjuntores trifásicos 30A e 40A
- [ ] Identificar para onde vão os cabos que saem do quadro da sede (R, S, T)
- [ ] Criar extensão para alimentar rack 19" do sistema canoas

**Comment by canoasadm** [comment]
Estou localizando as plantas
