### ISSUE TITLE
Sensor castelo não responde

### ISSUE THREAD

**Issue by josemotta** [recreiocanoas/radar#9]
:sparkles: **Verificação Sensor**
Local: **Castelo**

Etapas:
- [x] Testes no local
- [ ] Roteador funcionando
- [ ] Sensor funcionando
- [x] Roteador funciona com power-cycle
- [x] Sensor funciona com power-cycle
- [ ] Sensor sustituído por reserva

**Comment by josemotta** [comment]
Visita técnica ao castelo com power-cycle tudo volta a funcionar. Falha provável em 2019-08-16 13:41, ver log abaixo após restauração.

Log Details (WARNING)
Mon Aug 19 2019 10:39:54 GMT-0300 (Brasilia Standard Time)
Ended unfinished session (id=19 from 2019-08-16 13:41:52.462865

**Comment by josemotta** [comment]
:sparkles: **Verificação Sensor**
Local: **Castelo**

Etapas:
- [x] Testes no local
- [x] Roteador funcionando
- [ ] Sensor funcionando
- [x] Roteador funciona com power-cycle
- [x] Sensor funciona com power-cycle
- [ ] Sensor sustituído por reserva

Após power-cycle o sensor voltou a funcionar.

**Comment by canoasadm** [comment]
instalado equipamento supervisor no castelo

**Comment by josemotta** [comment]
Supervisor v1.0 com equipamento IoT-Home-L1 instalado na torre do Castelo, conectado via cabo par trançado ao switch. Sensor "super" medindo ambiente externo na área do Castelo. Sensor RPI0W-1 instalado com statestream ativado.

Com isso, sensor respondendo normalmente a partir de 30/08/2019 às 3:03 da tarde.

**Comment by josemotta** [comment]
Sensor não respondeu durante fds. Foi substituído o Access Point TEW-735AP pelo TEW-630APB. Após power cycle voltou a funcionar normalmente.
